CREATE TABLE `test` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='测试表'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;

CREATE TABLE `user` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NOT NULL,
	`password` VARCHAR(128) NOT NULL,
	`email` VARCHAR(128) NULL DEFAULT NULL,
	`mobile` VARCHAR(11) NULL DEFAULT NULL,
	`country_code` VARCHAR(10) NULL DEFAULT 'CN',
	`address` VARCHAR(128) NULL DEFAULT NULL,
	`enabled` BIT(1) NOT NULL DEFAULT b'1',
	PRIMARY KEY (`id`)
)
	COMMENT='用户表'
	COLLATE='utf8mb4_unicode_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=1
;


CREATE TABLE `group` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`group_name` VARCHAR(50) NOT NULL COMMENT '组名称',
	PRIMARY KEY (`id`)
)
	COMMENT='分组表'
	COLLATE='utf8mb4_unicode_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=1
;

CREATE TABLE `group_user` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`group_id` INT(10) UNSIGNED NOT NULL,
	`user_id` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
)
	COMMENT='用户组关系表'
	COLLATE='utf8mb4_unicode_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=1
;

CREATE TABLE `authority` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '用户ID',
	`authority` VARCHAR(50) NOT NULL COMMENT '权限代码',
	PRIMARY KEY (`id`)
)
	COMMENT='权限表'
	COLLATE='utf8mb4_unicode_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=1
;

CREATE TABLE `group_authority` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`group_id` INT(10) UNSIGNED NOT NULL,
	`authority_id` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`id`)
)
	COMMENT='组权限关系表'
	COLLATE='utf8mb4_unicode_ci'
	ENGINE=InnoDB
	AUTO_INCREMENT=1
;

