CREATE TABLE `test` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`content` VARCHAR(500) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='测试表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
